FROM registry.redhat.io/ubi9/nodejs-22
ENV NODE_ENV=production


RUN mkdir -p ./app
WORKDIR ./app

#COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
COPY ["package.json", "npm-shrinkwrap.json*", "./"]
# force use npm new version
RUN npm install --location=global npm@latest
RUN npm install --production --silent && mv node_modules ../
# RUN npm install

COPY . .
EXPOSE 8080
USER 1001
CMD ["npm", "start"]
